### ISSUE TITLE
Simplify version bump

### ISSUE THREAD

**Issue by Gerold103** [tarantool/rocks.tarantool.org#12]
I work with rocks once per several months usually. And I always forget how to update version of vshard. Or I just got used to it, and now everything is changed to curl and upload to the site, and I don't know how to do it again, what is rocks file expected syntax, options, etc. This frustrates me, and I just skip update, and don't do anything until someone asks explicitly.

It would be very helpful, if bump of a version of a module would be simplified to a click somewhere in a private office on the site.

**Comment by rosik** [comment]
I guess this issue is resolved after enabling uploading with CI in your project.
