### ISSUE TITLE
[2pt] Keep /manifest-5.1 updated to /manifest

### ISSUE THREAD

**Issue by ochaton** [tarantool/rocks.tarantool.org#28]
following command (with --lua-version 5.1) requires /manifest-5.1 to exist for some cases.
```bash
luarocks --lua-version 5.1 --only-server http://rocks.tarantool.org install checks
```

Please upload manifest-5.1 to rocks.tarantool.org and keep it updated to manifest

**Comment by rosik** [comment]
The problem isn't in `manifest-5.1` itself, it's already available. There must be something about `.zip`.

@ochaton could you provide `--verbose` log, please. And luarocks version too.

At least for me, it works fine with luarocks 3.
