### ISSUE TITLE
Refactor delete method

### ISSUE THREAD

**Issue by rosik** [tarantool/rocks.tarantool.org#9]
Current curl syntax is ambiguous (`curl -X DELETE -d '{"file_name":"mymodule-scm-1.src.rock"}' -H "Content-Type: application/json" http://rocks.tarantool.org`)

Instead it should be 
`curl -X DELETE http://rocks.tarantool.org/mymodule-scm-1.src.rock`

**Comment by artembo** [comment]
Closing because of #37
